<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
  <!-- Generated via Iro -->
  <dict>
    <key>fileTypes</key>
    <array>
      <string>meme</string>
    </array>
    <key>name</key>
    <string>memelang</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#main</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.memelang</string>
    <key>uuid</key>
    <string></string>
    <key>repository</key>
    <dict>
      <key>main</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(//.*)</string>
            <key>name</key>
            <string>comment.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(fn|intf|impl|struct|enum)(\s+)([a-zA-Z_]+[a-zA-Z0-9_]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.memelang</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.memelang</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.memelang</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(var|i8|i16|i32|u8|u16|u32|bool|impl|intf|struct|enum|fn)</string>
            <key>name</key>
            <string>storage.type.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(static|auto|const)</string>
            <key>name</key>
            <string>storage.modifier.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(return|for|if|match)</string>
            <key>name</key>
            <string>keyword.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([a-zA-Z_]+[a-zA-Z0-9_]*)(\s*)(\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.memelang</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>text.memelang</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.memelang</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b\d+)</string>
            <key>name</key>
            <string>constant.numeric.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(true|false)</string>
            <key>name</key>
            <string>constant.language.memelang</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.memelang</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#main__1</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.memelang</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>([\x{003a}\x{003d}\x{003c}\x{003e}\-\x{002b}\x{002a}\x{002f}\x{0025}\x{007c}\x{0021}\x{0026}.\x{003f}\x{007e}\x{005e}])</string>
            <key>name</key>
            <string>keyword.operator.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([\x{003b}\x{0028}\x{0029}\x{007b}\x{007d}\x{003c}\x{003e}\x{002c}\[\]])</string>
            <key>name</key>
            <string>punctuation.memelang</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\&quot;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.memelang</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#main__2</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\&quot;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.memelang</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\&apos;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.memelang</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#main__3</string>
              </dict>
            </array>
            <key>end</key>
            <string>(\&apos;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.memelang</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>([a-zA-Z_]+[a-zA-Z0-9_]*)</string>
            <key>name</key>
            <string>text.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^\s])</string>
            <key>name</key>
            <string>invalid.memelang</string>
          </dict>
        </array>
      </dict>
      <key>main__1</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
        </array>
      </dict>
      <key>main__2</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\\(?:\\|&quot;|&apos;))</string>
            <key>name</key>
            <string>text.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^\x{0027}\x{0022}\x{005c}]+)</string>
            <key>name</key>
            <string>text.memelang</string>
          </dict>
        </array>
      </dict>
      <key>main__3</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\\(?:\\|&apos;|&quot;))</string>
            <key>name</key>
            <string>text.memelang</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^\x{0027}\x{0022}\x{005c}]+)</string>
            <key>name</key>
            <string>text.memelang</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
